import {
  FaReact,
  FaNodeJs,
  FaDocker,
  FaAws,
  FaPython,
  FaGitAlt,
  FaFigma,
  FaHtml5,
  FaCss3Alt,
  FaDatabase,
  FaBrain,
  FaCogs,
} from "react-icons/fa";
import {
  SiTypescript,
  SiJavascript,
  SiMongodb,
  SiPostgresql,
  SiRedis,
  SiGraphql,
  SiNextdotjs,
  SiTailwindcss,
  SiExpress,
  SiKubernetes,
  SiFirebase,
  SiPytorch,
  SiTensorflow,
  SiOpenai,
  SiExpo,
  SiSocketdotio,
} from "react-icons/si";
import { DiMysql } from "react-icons/di";
import { TbApi, TbBrandReactNative, TbTopologyStar3 } from "react-icons/tb";

// Tech icon mapping with react-icons
export const techIcons: Record<string, any> = {
  React: FaReact,
  "Next.js": SiNextdotjs,
  TypeScript: SiTypescript,
  JavaScript: SiJavascript,
  "Tailwind CSS": SiTailwindcss,
  HTML5: FaHtml5,
  CSS3: FaCss3Alt,
  "Node.js": FaNodeJs,
  Express: SiExpress,
  "REST APIs": TbApi,
  WebSockets: SiSocketdotio,
  PostgreSQL: SiPostgresql,
  MongoDB: SiMongodb,
  MySQL: DiMysql,
  Redis: SiRedis,
  GraphQL: SiGraphql,
  AWS: FaAws,
  Docker: FaDocker,
  Kubernetes: SiKubernetes,
  Git: FaGitAlt,
  "CI/CD": FaCogs,
  Python: FaPython,
  "React Native": TbBrandReactNative,
  Expo: SiExpo,
  Firebase: SiFirebase,
  Figma: FaFigma,
  "PyTorch": SiPytorch,
  TensorFlow: SiTensorflow,
  "OpenAI API": SiOpenai,
  LangChain: TbTopologyStar3,
};

export const skills = [
  {
    id: 1,
    category: "FRONTEND",
    tech: [
      "React",
      "Next.js",
      "TypeScript",
      "JavaScript",
      "Tailwind CSS",
    ],
    icon: FaReact,
  },
  {
    id: 2,
    category: "BACKEND",
    tech: [
      "Node.js",
      "Express",
      "GraphQL",
      "REST APIs",
      "WebSockets",
    ],
    icon: FaNodeJs,
  },
  {
    id: 3,
    category: "DATABASES",
    tech: ["PostgreSQL", "MySQL", "MongoDB", "Redis"],
    icon: FaDatabase,
  },
  {
    id: 4,
    category: "DEVOPS & TOOLS",
    tech: ["AWS", "Docker", "Kubernetes", "Git", "CI/CD"],
    icon: FaAws,
  },
  {
    id: 5,
    category: "AI TECH STACK",
    tech: ["Python", "PyTorch", "TensorFlow", "LangChain", "OpenAI API"],
    icon: FaBrain,
  },
  {
    id: 6,
    category: "MOBILE & DESIGN",
    tech: ["React Native", "Expo", "TypeScript", "Firebase", "Figma"],
    icon: TbBrandReactNative,
  },
];
